### ISSUE TITLE
Typo in limb_darkening.py

### ISSUE THREAD

**Issue by guangweifu** [hrwakeford/ExoTiC-ISM#107]
On line 260, I think it should be reading the **G102**.WFC3.sensitivity.sav file instead of the **G141**.WFC3.sensitivity.sav file.

**Comment by ivalaginja** [comment]
Hi @guangweifu, thanks for opening this issue! What file exactly are you referring to?

**Comment by guangweifu** [comment]
It is just a typo in the lim_darkening.py code on line 260. The code is calling the G141 instead of the G102 sensitivity.sav file.

**Comment by ivalaginja** [comment]
Ok, I will look into it.

**Comment by ivalaginja** [comment]
You're totally right, that's a typo that needed to be fixed. I merged this into develop with PR #108, so it should be good to go now! Thanks for reporting this!
