### ISSUE TITLE
Save Wavelength Information in marginalisation.py .npz files

### ISSUE THREAD

**Issue by lili-alderson** [hrwakeford/ExoTiC-ISM#120]
To plot transmission spectra from `marginalisation.py` wavelength information needs to be stored in the .npz files (presumably `_marginalization_results.npz`)

Ideally the centre and half-width of the wavelength file input both need to be available so they can be called alongside `marg_rl` and `marg_rl_err`

**Comment by lili-alderson** [comment]
@hrwakeford

**Comment by hrwakeford** [comment]
I will address this in a PR as soon as I can.

**Comment by hrwakeford** [comment]
This issue was resolved in PR #121
