### ISSUE TITLE
Make the repo a package

### ISSUE THREAD

**Issue by ivalaginja** [hrwakeford/ExoTiC-ISM#55]
We should turn the repository into a full package, and we can use templates for it. The `astropy` package template is an option:
https://docs.astropy.org/projects/package-template/en/latest/

This would also take care of the docs (#29), while setting up continuous integration (#28) and a `setup.py` file.

**Comment by ivalaginja** [comment]
The resource listed in the PR description might be a little bit of an overkill for now. We have an intro tutorial notebook and the readme as docs for now, and the CI is not super critical either. In any case, preliminary test were merged with #68 so we could try setting up just the CI. For now I will bump this off the milestone.

**Comment by ivalaginja** [comment]
CI was set up with #87 and docs have their own issue, so here we should focusing on releasing the repo as a package on PyPI - which we should do with the next release, which will happen with the JOSS paper.

**Comment by ivalaginja** [comment]
@hrwakeford I just realized that we currently rely on the configfile to run anything with exoticism, so releasing it on PyPI or conda is not straightforward. Is it ok if I push this issue to a later point when we can reevaluate whether and how to make the repo an installable package?

**Comment by hrwakeford** [comment]
Yes I think that if needed we can push this down the road a little, but I think that the ability to run it as a package will make it more useable so we should use this issue to work out what aspects of the config file make it less flexible and how we can change those in a way to make it more versatile.

**Comment by ivalaginja** [comment]
I fully agree, and I also think it's worth it.

**Comment by ivalaginja** [comment]
Closed with #90
