### ISSUE TITLE
README ordering

### ISSUE THREAD

**Issue by hrwakeford** [hrwakeford/ExoTiC-ISM#76]
Overall setup and prerequisite need to come first in the set-up steps. If you have a new user like myself they will just blindly follow the steps in the Quickstart and then find that they have not installed everything in its own environment yet and have to redo things. 

If this is not the case and I am missing what the point of the prerequisite and QuickStart are for then we need to improve the language to make it clearer.

**Comment by ivalaginja** [comment]
Closed with #77
