### ISSUE TITLE
Spelling of marginalization throughout the code and documentation

### ISSUE THREAD

**Issue by hrwakeford** [hrwakeford/ExoTiC-ISM#89]
The spelling of marginalization alternates throughout the code and documentation. Right now all the documentation and paper is marginalisation with an ‘s’ but the code is marginalization with a ‘z’ and therefore following the set-up list and running the code does not work directly. Here are the issues I had:

> Run the marginalisation on the demo data from the template:
> $ python marginalisation.py

The file is called marginalization.py with a z
Once the code is run under the right spelling this error occurs

>  File "marginalization.py", line 32, in <module>
>     from exoticism.config import CONFIG_INI
> ModuleNotFoundError: No module named 'exoticism'

And it gets no further than this.

I suggest we go through and change it all - I have put out a twitter poll to see what people suggest for our choice
https://twitter.com/StellarPlanet/status/1244920506609958915?ref_src=twsrc%5Etfw

**Comment by ivalaginja** [comment]
@hrwakeford This is taken care of in the notebook PR #8!
