### ISSUE TITLE
Increase CI test coverage

### ISSUE THREAD

**Issue by ivalaginja** [hrwakeford/ExoTiC-ISM#96]
We have set up CI with GitHub Actions which runs on every open PR, however our code coverage is extremely low and should be increased in the future to ensure robustness with new code and updates.

**Comment by ivalaginja** [comment]
Regression tests would be the most important ones I think. Those kind of test make sure that the results from running the full analysis are the same like in a previously run analysis that we confirmed to be true.

@hrwakeford it seems to me like it would be fairly easy to write some simple regression tests, as we would just be comparing numbers to numbers, e.g. the results for the marginalised parameters. I could start writing this for W17 in the case of `fit_time`. Does that make sense to you or would you prefer I choose a different case as our benchmark?

**Comment by hrwakeford** [comment]
I think that `fit_time` is the perfect thing to test it on as that will be used most often. The most comprehensive would be `fit_all` but that would not be needed in this simple "does it work" test.

**Comment by hrwakeford** [comment]
@ivalaginja Can we close this issue now?

**Comment by hrwakeford** [comment]
yes this can now be closed
